import Foundation

/// Curated Czech diminutives (hypokoristika) -> the calendar name they
/// belong to. Only high-confidence mappings are listed; gender-ambiguous
/// nicknames (Peťa, Kája, Pája, Saša…) are intentionally left out – the
/// user can assign those manually. Names missing here still get a chance
/// through fuzzy stem matching in NameMatching.
///
/// Targets are resolved against the calendar at runtime; an entry whose
/// target is not in the calendar is silently ignored.
enum Diminutives {
	static let map: [String: String] = [
		// Mužská jména
		"honza": "Jan",
		"honzík": "Jan",
		"jenda": "Jan",
		"pepa": "Josef",
		"pepík": "Josef",
		"pepíček": "Josef",
		"vašek": "Václav",
		"vašík": "Václav",
		"venca": "Václav",
		"tonda": "Antonín",
		"toník": "Antonín",
		"franta": "František",
		"fanda": "František",
		"lojza": "Alois",
		"jarda": "Jaroslav",
		"standa": "Stanislav",
		"ruda": "Rudolf",
		"láďa": "Ladislav",
		"ladík": "Ladislav",
		"vláďa": "Vladimír",
		"míra": "Miroslav",
		"mirek": "Miroslav",
		"jirka": "Jiří",
		"jiřík": "Jiří",
		"ondra": "Ondřej",
		"kuba": "Jakub",
		"kubík": "Jakub",
		"ríša": "Richard",
		"zdenda": "Zdeněk",
		"milda": "Miloslav",
		"vojta": "Vojtěch",
		"olda": "Oldřich",
		"jindra": "Jindřich",
		"ferda": "Ferdinand",
		"bohouš": "Bohumil",
		"gusta": "Gustav",
		// Ženská jména
		"káťa": "Kateřina",
		"katka": "Kateřina",
		"kačka": "Kateřina",
		"kačenka": "Kateřina",
		"helča": "Helena",
		"terka": "Tereza",
		"terinka": "Tereza",
		"verča": "Veronika",
		"verunka": "Veronika",
		"barča": "Barbora",
		"barunka": "Barbora",
		"máňa": "Marie",
		"maruška": "Marie",
		"majka": "Marie",
		"mája": "Marie",
		"madla": "Magdaléna",
		"alča": "Alena",
		"ivča": "Ivana",
		"ivka": "Iva",
		"danča": "Daniela",
		"domča": "Dominika",
		"týna": "Kristýna",
		"týnka": "Kristýna",
		"nikča": "Nikola",
		"nikol": "Nikola",
		"hanka": "Hana",
		"hanča": "Hana",
		"janča": "Jana",
		"janička": "Jana",
		"anička": "Anna",
		"anča": "Anna",
		"andula": "Anna",
		"evča": "Eva",
		"evička": "Eva",
		"lída": "Ludmila",
		"líba": "Libuše",
		"růža": "Růžena",
		"zdena": "Zdeňka",
		"zdenička": "Zdeňka",
		"gabča": "Gabriela",
		"elča": "Eliška",
		"romča": "Romana",
		"simča": "Simona",
		"monča": "Monika",
		"ilča": "Ilona",
		"renča": "Renata",
		"lucka": "Lucie",
		"míša": "Michaela",
		"natka": "Natálie",
		"naty": "Natálie",
		"vendy": "Vendula",
		"jituška": "Jitka",
	]
}
